# monitoring/alertmanager-slack-alertmanager-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-webhook
  namespace: monitoring
type: Opaque
stringData:
  slack_webhook_url: "https://hooks.slack.com/services/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"
