grafana:
  adminPassword: admin
  service:
    type: ClusterIP

prometheus:
  service:
    type: ClusterIP

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: slack-notifications
      group_by: [ 'alertname', 'namespace' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
        - matchers:
            - severity="warning"
          receiver: slack-notifications
    receivers:
      - name: slack-notifications
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/slack_webhook_url
            channel: '#alerts'
            send_resolved: true
    inhibit_rules:
      - source_matchers: [ severity="critical" ]
        target_matchers: [ severity="warning" ]
        equal: [ 'alertname', 'namespace' ]
    alertmanagerSpec:
      secrets:
        - alertmanager-slack-webhook
  service:
    type: ClusterIP

additionalPrometheusRulesMap:
  spring-app-probes:
    groups:
      - name: spring-boot-health.rules
        rules:
          - alert: ContainerRestartSpike
            expr: |
              increase(kube_pod_container_status_restarts_total{namespace=~"fdp-.*|mod-.*|inc-.*|bulk-.*"}[10m]) > 3
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Container restart spike"
              description: "Container '{{ $labels.container }}' in pod '{{ $labels.pod }}' (ns: '{{ $labels.namespace }}') restarted more than 3 times in 10 minutes."

          - alert: ContainerNotReady
            expr: |
              kube_pod_container_status_ready{namespace=~"fdp-.*|mod-.*|inc-.*|bulk-.*"} == 0
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Container not ready"
              description: "Container '{{ $labels.container }}' in pod '{{ $labels.pod }}' (ns: '{{ $labels.namespace }}') has failed readiness probe for more than 5 minutes."

          - alert: AlwaysFiring
            expr: vector(1)
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Test Slack alert"
              description: "This is a test alert for Slack routing."
